### ISSUE TITLE
Add an onboarding game

### ISSUE THREAD

**Issue by chrismytton** [everypolitician/gender-crowdsourcing#17]
On-boarding game with non-politicians to introduce people to the game. E.g. use someone that is reasonably well known, who could be mistaken for the wrong gender and warn the person not to guess if they choose the wrong gender.

**Comment by zarino** [comment]
@chrismytton: is there currently a way for me to tell whether the user is "new" or has voted before?

**Comment by chrismytton** [comment]
@zarino Yep, you can check if the `current_user` has any responses, if they have then they've voted before:

```erb
<% if current_user.responses.any? %>
  User has voted before
<% else %>
  User has never voted
<% end %>
```

**Comment by zarino** [comment]
I'm thinking maybe we just do this as a static page, essentially a copy of the normal "country" page, except the cards are full of example people, and some of the cards are informational. Like, you could have a card saying "Rather than using the buttons, you can swipe cards left or right to categorise as Male or Female. Try swiping this card left…" and then once they've completed the command, the card below is shown, as normal. That sort of thing?

**Comment by chrismytton** [comment]
@zarino Yep a static page sounds sensible to me. We don't need to store the answers or anything so it can pretty much just be a javascript driven introduction screen.

**Comment by zarino** [comment]
https://github.com/everypolitician/gender-crowdsourcing/commit/5055c7d59cac39e2c7308ebeb3cba9269596677a adds a basic onboarding game.

Improvements that could be made:
* [#71](https://github.com/everypolitician/gender-crowdsourcing/issues/71) – Use real politicians in the onboarding game
* [#71](https://github.com/everypolitician/gender-crowdsourcing/issues/72) – Check (and correct) the user’s answers in the onboarding game
