### ISSUE TITLE
Search box at top of "Pick a country" page to live filter the list

### ISSUE THREAD

**Issue by zarino** [everypolitician/gender-crowdsourcing#40]
There are 70-odd countries at the moment, and it already feels quite unwieldy, especially when you first start (and thus can't click the "recent country" shortcut at the top).

Maybe a filter at the top, so you could start typing the country name. It could even use the same "alternative names" logic as the search box on the everypolitician homepage.

**Comment by tmtmtmtm** [comment]
Could we also move whatever country the person currently seems to be in to the top? That sort of thing is really annoying if it _forces_ you into something (I'm looking at Google, who should really know by now that I want the English version of their sites no matter what country I currently happen to be in), but simply promoting it to the top of a list seems much friendlier…

**Comment by zarino** [comment]
I was going to say, a "Suggested countries" seems sensible, but I couldn't think of a quick way of doing it, given the data we have.

**Comment by tmtmtmtm** [comment]
At least some of the social auths will give us location info if set, no? And I thought there were fairly decent drop-in ip-to-country lookups that are Good Enough™ for things like this? It's a long time since I've looked into this sort of thing though, so if it's non-trivial, it's probably not worth it.
